In [1]:
# BoW

In [2]:
documents = [
    "I eat mango",
    "i love mango."
]

In [3]:
lower_case_documents = []

for i in documents:
    # print(i)
    lower_case_documents.append(i.lower())
print(lower_case_documents)

['i eat mango', 'i love mango.']


In [4]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [5]:
punctuation_removed_documents = []

for i in lower_case_documents:
    s = ''
    for j in i:
        if j not in string.punctuation:
            s = s + j
    # print(s)
    punctuation_removed_documents.append(s)

punctuation_removed_documents

['i eat mango', 'i love mango']

In [6]:
preprocessed_documents = []

for i in punctuation_removed_documents:
    preprocessed_documents.append(i.split(' '))

preprocessed_documents

[['i', 'eat', 'mango'], ['i', 'love', 'mango']]

In [7]:
# ... map

In [8]:
# BoW Using Library ...

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()
count_vector.fit_transform(documents).toarray()

array([[1, 0, 1],
       [0, 1, 1]])

In [10]:
# stopwords are commonly used words that have no value in NLP (I, a, on ... )

count_vector.get_feature_names_out()

array(['eat', 'love', 'mango'], dtype=object)

In [11]:
# Pandas Dataframe ..

import pandas as pd

df = pd.DataFrame(count_vector.fit_transform(documents).toarray(), columns=count_vector.get_feature_names_out())

df.head()

eat  love  mango
0    1     0      1
1    0     1      1

In [12]:
# https://saturncloud.io/blog/a-list-of-pandas-readcsv-encoding-options/

df = pd.read_csv('/kaggle/input/sms-spam-collection-dataset/spam.csv', encoding='latin1')
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [14]:
df = df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1)

In [15]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [16]:
# rename
df = df.rename(columns={"v1": "target", "v2": "text"})

In [17]:
df.head()

target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()
count_vector.fit(df['text'])
text_features = count_vector.transform(df['text']).toarray()

In [19]:
text_features

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
def fun(value):
    if value=='ham':
        return 0
    return 1

In [21]:
df['target'] = df['target'].apply(fun)

In [22]:
X = text_features
y = df['target']

In [23]:
# df.head()

In [24]:
# Generic Step

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=1)

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
model = MultinomialNB()

In [28]:
model.fit(X_train,y_train)

MultinomialNB()

In [29]:
model.score(X_test,y_test)

0.97847533632287

In [30]:
# ??

In [31]:
sentence = "Free entry in wkly comp"
text_features = count_vector.transform([sentence]).toarray()
text_features

array([[0, 0, 0, ..., 0, 0, 0]])

In [32]:
model.predict(text_features)

array([1])

In [33]:
model.predict_proba(text_features)

array([[3.11208245e-04, 9.99688792e-01]])

In [34]:
import numpy as np
np.argmax(model.predict_proba(text_features))

1

In [35]:
1

1